version: '3.1'
services:
  jupyter:
    image: daehyunpy/sp8-delayline
    command:
      - jupyter
      - lab
      - --allow-root
      - --config=/app/jupyter_notebook_config.json
    ports:
      - 18888:8888
    volumes:
      - .:/data
    secrets:
      - source: config
        target: /app/jupyter_notebook_config.json
secrets:
  config:
    file: ./jupyter_notebook_config.json
