version: '2'
services:
  jupyter:
    user: 1001:1001
    group_add:
      - 1001
      - 2000
    environment:
      HOME: /app
      JAVA_TOOL_OPTIONS: -Duser.home=/app
    ports:
      - 4040
      - 7777:8888
    volumes:
      - ./site-packages:/app/site-packages
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /home/notebook:/data
      - /home/notebook:/home/notebook
      - /home/fukuzawa:/home/fukuzawa
      - /home/daehyun:/home/daehyun
      - /home/saito:/home/saito
      - /home/luo:/home/luo
      - /helium:/helium
  mongodb:
    ports:
      - 27017
