version: '2'
services:
  jupyter:
    ports:
      - 4040
      - 8888:8888
    volumes:
      - ./site-packages:/app/.local/lib/python3.6/site-packages
      - ~/.jupyter:/app/.jupyter
  mongodb:
    ports:
      - 27017:27017
