version: '2'
services:
  jupyter:
    image: daehyunpy/playground-python:v201809.2
    restart: unless-stopped
    command:
      - python
      - -m
      - jupyter
      - lab
      - --allow-root
      - --config=/app/jupyter_notebook_config.json
    volumes:
      - ./jupyter_notebook_config.json:/app/jupyter_notebook_config.json:ro
      - ./local.pth:/app/.venv/lib/python3.6/site-packages/local.pth:ro
      - .:/data
    links:
      - mongodb
  mongodb:
    image: mongo
    restart: unless-stopped
    volumes: 
      - ./MongoDB:/data/db
